### ISSUE TITLE
Not able to switch to a different broker than "localhost:9092"

### ISSUE THREAD

**Issue by bensbox** [krux/tcp-stream-kafka-producer#10]
Hi everybody,

i am currently playing around with your stream producer. When i am running kafka on the same machine as the producer, then the default settings for metadata.broker.list ("localhost:9092") will apply and everything is working just fine.

My problem is, when i am trying to use a different kafka-broker-host. The flag "--metadata.broker.list" doesn't work for changing the host ("--metadata.broker.list \<ip-or-hostname\>:9092") and/or for a different port ("--metadata.broker.list \<localhost-or-ip-or-hostname\>:1500").

Is this a bug or am i using it wrong :)

Thanks!

**Comment by prashuj** [comment]
Firstly, thanks for giving it a try :)

The way to pass the broker info is
--metadata.broker.list host1:port1,host2:port2 ...

Take a look at --help

--metadata.broker.list                       This is for bootstrapping and the producer will only use 
                                               it for getting metadata (topics, partitions and        
                                               replicas). The socket connections for sending the      
                                               actual data will be established based on the broker    
                                               information returned in the metadata. The format is    
                                               host1:port1,host2:port2, and the list can be a subset  
                                               of brokers or a VIP pointing to a subset of brokers.   
                                               (default: localhost:9092)

**Comment by bensbox** [comment]
@prashuj - please have another look at my post ..i used \<html-tag-style\> formatting without escaping the \< signs ..it showed "\<ip-or-hostname\>:9092" as ":9092"

**Comment by bensbox** [comment]
I tried:

1. --metadata.broker.list localhost:9092
2. --metadata.broker.list \<ip-of-other-host\>:9092
3. --metadata.broker.list \<name-of-other-host\>:9092
4. --metadata.broker.list localhost:\<other-port\>
5. --metadata.broker.list \<ip-of-other-host\>:\<other-port\>

Only 1. is working

**Comment by prashuj** [comment]
Currently the code is structured to start the listeners only if --heartbeat-topic is specified (we will fix this shortly). For now make sure, you pass in a heartbeat-topic to which a test message is written every second.

Along with --heartbeat-topic pass in --metadata.broker.list arg as before.

Very recently, for heartbeat messages, metadata.broker.list arg was to fixed to take in hostnames other than localhost. Please pull in the latest changes.

Example args:

--heartbeat-topic heartbeat_topic --port.topic 32344:test_topic --always-accept-streams --metadata.broker.list host1:9092,host2:9092

**Comment by bensbox** [comment]
Yeah i already figured that out, that you need to specifiy the heartbeat-topic :)

Well, the latest changes fixed the problem - thanks for that. In v1.3.1 it didn't work - in v1.3.2 it seems to be fine.

I will test this now and close the ticket as soon as i fully confirmed it.

Thanks :)

**Comment by bensbox** [comment]
btw - it would be nice, if you could add some more logging about trying to connect to the kafka server, or if there are connection tries to the stream ports etc.

**Comment by bensbox** [comment]
@prashuj Problem is fixed - thanks for the help!

**Comment by prashuj** [comment]
Your welcome!
